# Generated by Django 5.2.6 on 2025-10-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_tag_alter_asset_options_asset_metadata_asset_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
