# Generated by Django 5.2.6 on 2025-10-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetversion_comment_assetversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versioned_assets', to='assets.category'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='versioned_assets', to='assets.tag'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
