# Generated by Django 5.2.6 on 2025-10-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetversion_category_assetversion_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
